# This is a minor modification to see if a build is triggered now
os: windows
language: cpp
env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
install:
  - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
script:
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe -t:Rebuild -p:Configuration=UnitTesting -p:AdditionalLibPaths=3rdParty\raylib\bin -p:Platform=x64 TemperComp/TemperComp.vcxproj
  - TemperComp\BuildOutput\UnitTesting\TemperComp.exe